name: pipeline_TDW-02

# Trigger on push or pull requests to any branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Setup Node.js environment with the specified version (18.x)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Ensure clean installation of dependencies using npm ci
    - name: Install dependencies
      run: npm ci  # Cleans and installs all dependencies based on package-lock.json

    # Step 4: Run the tests
    - name: Run tests
      run: npm test  # Assumes tests are defined in package.json scripts

    # Step 5: Build the project
    - name: Build project
      run: npm run build  # Ensures the Next.js build command runs
